-- AI Content Creation Track: 5 modules × 5 lessons = 25 lessons
-- All modules go under the 'money' path since these are income skills
-- Pro modules are orders 6-25, AI Career modules start at order 26

-- ============================================================
-- TRACK: AI Content Creation (modules 26-30)
-- ============================================================

insert into public.modules (path_id, title, description, "order")
select p.id, m.title, m.description, m.ord
from public.paths p
cross join (values
  ('AI Writing and Copywriting', 'Master AI-powered writing tools to produce professional sales copy, blog content, social media captions, and email campaigns that win clients and grow businesses.', 26),
  ('AI Visual Content', 'Use AI design and image generation tools to create stunning marketing visuals, brand assets, and social media content faster than traditional designers.', 27),
  ('AI Video and Shorts', 'Build a video content production system using AI for scripting, editing, voiceover, and publishing — no expensive equipment or on-camera presence required.', 28),
  ('AI Social Media Management', 'Combine AI tools with social media strategy to manage multiple client accounts efficiently and deliver measurable results.', 29),
  ('Building an AI Content Agency', 'Scale from solo AI content creator to agency owner with productized services, team members, and recurring revenue exceeding 100K pesos per month.', 30)
) as m(title, description, ord)
where p.pillar = 'money';


-- ============================================================
-- MODULE 1 LESSONS: AI Writing and Copywriting
-- ============================================================

-- Lesson 1
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Your First AI-Written Sales Copy',
  'The Philippine e-commerce market hit ₱750 billion in 2025, and every seller on Shopee, Lazada, and Facebook Marketplace needs compelling product descriptions, ad copy, and email sequences to convert browsers into buyers. Most small Filipino business owners write their own copy — and it shows. Awkward phrasing, missing benefits, no call to action. This is your opportunity. Using AI tools like Claude and ChatGPT, you can produce professional sales copy in minutes that would take a traditional copywriter hours. The secret is prompt engineering — giving the AI the right instructions to produce the right output. A well-crafted prompt includes the target audience (e.g., "Filipino mothers aged 25-35 in Metro Manila"), the product benefits (not features), the desired tone (conversational Taglish, professional English, or casual Filipino), and the format (headline + body + CTA). Start with product descriptions: take any Shopee listing with a bland description, feed the product details into Claude with a prompt like "Write a compelling Shopee product description for Filipino buyers, 150 words, highlight benefits not features, include a sense of urgency." The output will be dramatically better than what 90% of sellers write themselves. Pricing for AI-enhanced copywriting in the Philippines ranges from ₱5,000 to ₱15,000 per project depending on scope. A single product description batch (20 listings) can earn you ₱8,000 in an afternoon. An email welcome sequence for a local business runs ₱5,000-₱10,000. Ad copy packages (10 Facebook ad variations) go for ₱3,000-₱7,000. The key is speed: what used to take days now takes hours, and your profit margin is enormous because your primary tool is free or low-cost. You are not replacing human creativity — you are amplifying it. You still need to review, edit, and refine every piece of AI output. The AI gives you the first draft in seconds; your expertise turns it into something that actually sells. Filipino clients care about results, not how you produce them. If your copy increases their sales, they will pay you gladly and refer you to others.',
  'Complete these steps today: (1) Create accounts on both Claude (claude.ai) and ChatGPT (chat.openai.com) — both have free tiers. (2) Find 3 Shopee listings in your area of interest that have weak product descriptions. (3) For each listing, write a prompt that includes: target customer, key product benefits, desired tone, and word count. (4) Generate improved descriptions using both Claude and ChatGPT — compare the outputs. (5) Save your best prompt templates in a Google Doc labeled "Copy Prompts Library" — you will build on this throughout the module.',
  'Which AI tool produced better results for Filipino-market copy — Claude or ChatGPT? What patterns did you notice in effective prompts versus ones that produced generic output? How does it feel to produce professional-quality copy this quickly?',
  1
from public.modules m where m.title = 'AI Writing and Copywriting';

-- Lesson 2
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Blog Posts and SEO Content with AI',
  'Google processes over 8.5 billion searches per day, and Filipino internet users spend an average of 10 hours online daily — one of the highest rates in the world. Businesses that rank on Google for local searches ("best derma clinic in Cebu," "affordable catering Manila") get free, consistent traffic that converts into customers. Blog content is how they rank, and most Philippine businesses have zero blog strategy. This is a massive gap you can fill with AI. The workflow is straightforward: research keywords using free tools like Google Keyword Planner or Ubersuggest, generate a detailed outline with Claude, then produce a full 1,500-2,000 word blog post that targets those keywords naturally. Tools like SurferSEO (paid) or NeuronWriter can help optimize your content for search rankings, but even without them, AI-generated content that is well-structured and edited for accuracy will outperform the thin, 300-word posts most Filipino businesses publish. Your editing process is critical. AI can hallucinate facts, produce repetitive paragraphs, and miss local nuances. Every AI-generated blog post needs your human review: verify all statistics and claims, add local examples and references (mention specific Philippine brands, locations, and cultural touchpoints), break up long paragraphs for mobile reading (85% of Filipino internet users are on mobile), and add internal links and calls to action. Client rates for SEO blog content in the Philippines range from ₱3 to ₱8 per word. A 1,500-word optimized blog post earns you ₱4,500 to ₱12,000. If you can produce 2-3 posts per day with AI assistance (versus 1 post per day writing manually), you are looking at ₱9,000 to ₱36,000 per day in potential revenue. Even at the conservative end, producing 10 posts per month for a single client at ₱5 per word generates ₱75,000 monthly. The key is positioning yourself as an SEO content strategist, not just a writer. You research keywords, plan content calendars, optimize for search, and track rankings. The AI is your production tool — the strategy is your value.',
  'Follow this process: (1) Pick a niche you know well — food, beauty, fitness, tech, or finance in the Philippines. (2) Use Google autocomplete and "People Also Ask" to find 10 blog topics Filipino users are searching for. (3) Choose one topic and use Claude to generate a detailed outline with H2 and H3 headings. (4) Generate the full blog post (1,500+ words) using AI, then spend 30 minutes editing: add local examples, verify facts, improve readability for mobile. (5) Save the finished post as a portfolio sample. Time yourself — the entire process should take under 90 minutes.',
  'How does AI-assisted blog writing compare to writing from scratch in terms of quality and speed? What parts of the editing process required the most human judgment? Could you see yourself producing content at this pace for multiple clients?',
  2
from public.modules m where m.title = 'AI Writing and Copywriting';

-- Lesson 3
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Social Media Captions at Scale',
  'The average Filipino spends 4 hours and 15 minutes on social media daily — more than any other country in the world. Facebook has 87 million users in the Philippines, Instagram is growing fast among the 18-34 demographic, and TikTok has exploded to over 50 million Filipino users. Every brand competing for attention on these platforms needs a constant stream of fresh, engaging captions. Most small businesses in the Philippines post inconsistently because writing captions feels time-consuming and creatively draining. With AI, you can batch-create 30 days of platform-specific captions in approximately 2 hours. The process works like this: first, understand the client brand voice and audience (a Makati coffee shop speaks differently than a Cebu surfing school). Second, create a content calendar with post themes — motivational Monday, product spotlight Wednesday, customer story Friday, weekend promo. Third, feed Claude a prompt with the brand voice, content theme, platform (Facebook is longer and more conversational, Instagram is hashtag-heavy and visual, TikTok is punchy and trend-driven), and desired caption length. Generate 5 variations per theme and pick the best. For Filipino audiences, Taglish (Tagalog-English mix) consistently outperforms pure English on engagement metrics. A caption that says "Grabe, ang sarap ng new menu namin — try mo na!" gets more likes and comments than "Try our delicious new menu today." Cultural references, local humor, and genuine warmth perform best. Avoid overly salesy language — Filipinos are sophisticated at detecting hard sells and respond better to authentic, relatable content. The business model: offer a "Social Media Caption Package" — 30 days of captions across 2-3 platforms for ₱5,000-₱12,000 per month. Tools you need: Claude for caption generation, Canva for pairing captions with visuals, and Buffer or Later (both have free tiers) for scheduling. Combine caption writing with visual creation (covered in Module 2) and you can charge ₱15,000-₱25,000 per month for a complete social media content package. At 3-4 clients, you are earning ₱45,000-₱100,000 monthly with approximately 15-20 hours of work per week.',
  'Do this exercise now: (1) Choose a real local business (restaurant, salon, gym, or shop) from your area. (2) Define their brand voice in 3 words (e.g., "warm, playful, authentic"). (3) Create a 7-day content calendar with themes for each day. (4) Use Claude to generate captions for all 7 days — create Facebook, Instagram, and TikTok versions of each. (5) Time yourself: aim to complete all 21 captions (7 days x 3 platforms) in under 60 minutes. Save these as portfolio samples.',
  'How did writing Taglish captions compare to English-only captions in terms of authenticity and engagement potential? Which platform was easiest to write captions for, and which was most challenging? What did you learn about adapting tone across platforms?',
  3
from public.modules m where m.title = 'AI Writing and Copywriting';

-- Lesson 4
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Email Marketing with AI',
  'Email marketing delivers an average return of ₱2,100 for every ₱50 spent — a 42:1 ROI that no other digital channel matches. Yet most Philippine small businesses do not have an email strategy beyond manually sending GCash payment confirmations. This is a premium service you can offer using AI. The core email sequences every business needs: a Welcome Sequence (3-5 emails that introduce the brand, deliver value, and make a first offer), a Promotional Sequence (3-4 emails for sales, new product launches, or events), an Abandoned Cart Sequence (2-3 emails for e-commerce recovering lost sales — these alone can recover 10-15% of abandoned carts), and a Nurture Newsletter (weekly or bi-weekly content that keeps subscribers engaged between promotions). AI makes building these sequences fast. For a welcome sequence, prompt Claude with: "Write a 5-email welcome sequence for [business type] in the Philippines. Target audience: [demographic]. Tone: warm, helpful, not pushy. Each email should be 150-200 words. Include subject lines with 40% open rate potential. Email 1: welcome and brand story. Email 2: top 3 tips related to their need. Email 3: customer success story. Email 4: introduce best-selling product. Email 5: special first-purchase offer." Then integrate with Mailchimp (free for up to 500 subscribers) or ConvertKit (free for up to 1,000 subscribers). These tools handle the automation — you set it up once and it runs forever. Pricing for email marketing services in the Philippines: Welcome sequence setup: ₱8,000-₱15,000. Monthly newsletter management: ₱5,000-₱10,000. Complete email automation setup (all sequences): ₱15,000-₱25,000. Monthly retainer for strategy plus execution: ₱8,000-₱20,000. A single client on a monthly retainer of ₱12,000 requires approximately 4-6 hours of your time per month — AI handles the heavy lifting of draft creation, and you focus on strategy, personalization, and performance analysis. The compounding power: once you build email templates and prompt libraries for common industries (restaurants, clinics, e-commerce stores), each new client requires less setup time. Your fifth restaurant client email system takes one-third the time of your first.',
  'Complete this project: (1) Sign up for Mailchimp free tier at mailchimp.com. (2) Choose a business type (restaurant, online shop, clinic, or fitness studio). (3) Use Claude to generate a complete 5-email welcome sequence with subject lines, preview text, body copy, and CTAs. (4) Edit each email for tone, accuracy, and local relevance. (5) Set up the sequence in Mailchimp as an automated workflow — even if you do not have real subscribers yet, this gives you hands-on platform experience and a portfolio piece to show clients.',
  'How does email marketing feel different from social media marketing? Which type of email was easiest to write with AI, and which required the most human editing? Can you see how offering email marketing would complement your other AI content services?',
  4
from public.modules m where m.title = 'AI Writing and Copywriting';

-- Lesson 5
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Building Your AI Writing Portfolio',
  'A portfolio is what separates "I can write" from "Hire me now." According to a 2025 Upwork Philippines survey, freelancers with a professional portfolio earn 2.3 times more than those without one. The good news: with AI, you can build a compelling 5-piece portfolio in a single weekend. Your portfolio needs to demonstrate range and results. Include these 5 pieces: (1) Product Description Set — 10 optimized Shopee or Lazada listings for a specific niche, showing before and after versions. (2) Blog Post — One 1,500-word SEO-optimized article with proper headings, meta description, and keyword strategy. (3) Social Media Package — 7 days of captions across Facebook, Instagram, and TikTok for a real local business. (4) Email Sequence — A 3-5 email welcome series for a specific business type. (5) Ad Copy Set — 5 Facebook ad variations (headline, body, CTA) for a product or service. Present your portfolio on a free website using Notion (notion.so), Carrd (carrd.co for ₱0-₱500/year), or Google Sites (free). Each piece should include: the brief (who the client is and what they needed), the final deliverable, and a short note on your process. Address the elephant in the room: the "just AI" stigma. Some clients worry that AI-generated content is generic or low quality. Your response: you use AI as a production tool (like a photographer uses Photoshop), but every piece is strategically planned, edited for brand voice, fact-checked, and optimized for the Philippine market. The AI writes the first draft; your expertise makes it convert. Pricing your services: do not charge by the hour — AI makes you fast, and hourly billing penalizes efficiency. Use project-based or package pricing. Starter packages: ₱5,000-₱8,000 for a content batch. Monthly retainers: ₱10,000-₱25,000 for ongoing content. Premium packages: ₱20,000-₱40,000 for complete content systems. Always anchor your price to the value you deliver. If your product descriptions help a Shopee seller increase conversions by even 10%, that could mean ₱50,000+ in additional revenue per month — your ₱8,000 fee is a bargain. Filipino clients respond well to clear deliverables, fast turnaround, and visible results. Deliver those consistently and referrals will become your primary client acquisition channel.',
  'Build your portfolio this weekend: (1) Create your portfolio website on Notion, Carrd, or Google Sites. (2) Generate all 5 portfolio pieces using the skills from lessons 1-4 — use real businesses as case studies (with a note that these are sample projects). (3) Write a one-paragraph bio that positions you as an AI-enhanced content specialist, not just a writer. (4) Create a simple pricing page with 3 tiers (Basic, Standard, Premium). (5) Share your portfolio link on your personal Facebook, LinkedIn, and in 2-3 relevant Filipino freelancer groups. Ask 3 trusted contacts for honest feedback.',
  'How does having a complete portfolio change your confidence in approaching potential clients? What was the hardest piece to create, and why? Looking at your 5 portfolio pieces together, what is your strongest type of content — and could that become your specialty?',
  5
from public.modules m where m.title = 'AI Writing and Copywriting';


-- ============================================================
-- MODULE 2 LESSONS: AI Visual Content
-- ============================================================

-- Lesson 1
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Canva AI for Professional Design',
  'Canva has over 170 million monthly active users worldwide, and it is the most popular design tool among Filipino freelancers and small businesses because of its free tier and intuitive interface. But most users barely scratch the surface. Canva AI features — Magic Design, text-to-image, background remover, Magic Eraser, Magic Write, and brand kits — transform you from a casual user into a professional-speed designer. Magic Design generates complete design layouts from a single text prompt or uploaded image. Instead of starting from a blank canvas, describe what you need: "Instagram post for a Manila milk tea shop grand opening, pink and white theme, fun and youthful." Canva generates multiple options in seconds. Text-to-image (powered by Stable Diffusion) creates custom illustrations and images when stock photos do not fit. Need a cartoon-style image of a Filipino family enjoying a meal? Generate it. Background Remover and Magic Eraser clean up product photos — essential for Shopee and Lazada listings where white backgrounds are standard. Magic Write helps generate text overlays, headlines, and short copy directly within your design. Brand Kits let you save client colors, fonts, and logos so every design stays on-brand with one click. The professional design workflow: (1) Client provides brief and brand assets. (2) You create a Brand Kit in Canva with their colors, fonts, and logo. (3) Use Magic Design to generate initial layouts. (4) Customize using templates, text-to-image for unique visuals, and background remover for product shots. (5) Export in the correct format for each platform (1080x1080 for Instagram, 1200x628 for Facebook ads, 1000x1000 for Shopee). Average delivery time using AI features: 15-20 minutes per design versus 45-60 minutes without. At ₱300-₱500 per design, producing 20 designs in a day earns you ₱6,000-₱10,000. Social media post packages (30 designs per month) typically sell for ₱5,000-₱12,000 in the Philippine market. Canva Pro costs ₱4,499/year — it pays for itself with a single client.',
  'Do this hands-on exercise: (1) If you do not have Canva Pro, start the 30-day free trial at canva.com. (2) Create a Brand Kit for a fictional Filipino business — choose a milk tea shop, salon, or gym. Add a color palette (3 colors), 2 fonts, and a simple logo (you can design one in Canva). (3) Use Magic Design to generate 5 social media posts for this business. (4) Use background remover on a product photo (download any product image from Google). (5) Use text-to-image to generate a custom illustration for one post. Time yourself — aim to finish all 5 posts in under 30 minutes.',
  'How much faster were you using Canva AI features compared to manual design? Which feature had the biggest impact on your workflow — Magic Design, background remover, or text-to-image? How could you combine these features to offer design services to local businesses?',
  1
from public.modules m where m.title = 'AI Visual Content';

-- Lesson 2
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'AI Image Generation for Business',
  'AI image generation has moved from novelty to professional tool. Midjourney, DALL-E (inside ChatGPT), and Stable Diffusion (free and open-source) can produce product mockups, marketing visuals, and brand imagery that previously required a professional photographer or graphic designer charging ₱15,000-₱50,000 per shoot. For Filipino businesses operating on tight budgets, this is a game-changer. Practical business applications: Product Mockups — generate lifestyle images showing your product in context without a photo shoot. A candle brand can get "cozy Filipino living room with candle on wooden table, warm lighting, modern minimalist" in seconds. Marketing Campaign Visuals — generate unique hero images for ads, banners, and promotions that stand out from generic stock photos. Brand Imagery — create consistent visual themes for social media without licensing expensive stock photos. Menu and Catalog Design — generate appetizing food imagery for restaurants that cannot afford food photographers. The tools differ in strengths: Midjourney (₱500-₱1,500/month) produces the most photorealistic and aesthetically pleasing images; DALL-E 3 (included in ChatGPT Plus at ₱1,100/month) is easiest to use with natural language prompts and excels at following specific instructions; Stable Diffusion (free) runs locally on your computer and offers unlimited generations with no subscription. Critical legal consideration: commercial use rights. Midjourney and DALL-E grant commercial use rights on paid plans. Stable Diffusion models vary — check the license of each model you use. Never represent AI-generated images as real photographs to clients. Always disclose that imagery is AI-generated when asked. Ethical use matters for long-term business reputation. Prompt engineering for images follows the pattern: subject + setting + style + lighting + mood + technical specs. Example: "Filipino woman in her 30s, professional office setting, using laptop, natural window light, warm tones, shot on Canon 5D, shallow depth of field." The more specific your prompt, the more usable the output. Build a prompt library organized by use case: product shots, lifestyle images, food photography, professional portraits, and abstract brand imagery. This library becomes one of your most valuable business assets over time.',
  'Experiment with all three tools: (1) Sign up for DALL-E via ChatGPT (free tier gives limited generations). (2) Try Midjourney via their Discord server (free trial available). (3) Generate the same image concept on both platforms — "Filipino coffee shop interior, warm lighting, modern minimalist, cozy atmosphere." Compare results. (4) Generate 3 product mockup images for a fictional Filipino skincare brand — a hero image, a lifestyle shot, and a flat-lay product arrangement. (5) Save your best prompts and results. Note which tool worked best for which type of image.',
  'Which AI image generator felt most natural to use, and which produced the most professional results? How could AI-generated images solve real problems for Filipino businesses you know? What ethical guidelines would you set for yourself when offering AI image generation services?',
  2
from public.modules m where m.title = 'AI Visual Content';

-- Lesson 3
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Thumbnail and Banner Design',
  'Thumbnails and banners are the billboards of the digital world — they determine whether someone clicks or scrolls past. YouTube reports that 90% of top-performing videos have custom thumbnails. Facebook ads with compelling visuals have a 2.3x higher click-through rate than those with generic images. On Shopee, listings with professional banners see 40% more clicks. For Filipino content creators and e-commerce sellers, investing in great thumbnails and banners directly translates to more views, more clicks, and more revenue. YouTube Thumbnail Formula: The most effective thumbnails combine a clear facial expression (curiosity, surprise, or excitement), bold text overlay (3-5 words maximum), contrasting colors (complementary colors pop — blue-orange, purple-yellow), and context clues about the video content. Using AI tools, you can generate or enhance thumbnail elements quickly. Use DALL-E or Midjourney for background imagery, Canva for text overlay and composition, and background remover to isolate subjects. Filipino-specific tip: thumbnails with Taglish text and local cultural cues (jeepney imagery, Filipino food, local landmarks) perform significantly better than generic Western-style thumbnails for a Filipino audience. Facebook Cover and Ad Banners: Standard sizes are 1200x628 for link ads and 1080x1080 for feed posts. The key is the "thumb-stop" factor — your banner has approximately 1.5 seconds to grab attention in the feed. AI-generated unique visuals stop thumbs faster than overused stock photos. Shopee Banners: Shopee allows shop banners (1200x300) and product banners within listings. High-performing Shopee shops have professional banners that communicate brand identity and current promotions. Most Filipino sellers use basic phone-shot photos — a professional banner immediately sets your shop apart. A/B testing is essential. Create 2-3 versions of each thumbnail or banner and test which performs better. YouTube has built-in A/B testing for thumbnails. For Facebook, run split tests with different ad creatives. For Shopee, rotate banners weekly and track click-through rates. The data tells you what your audience responds to, removing guesswork from design decisions. Pricing: thumbnail packages (10 YouTube thumbnails) sell for ₱3,000-₱5,000. Banner design packages start at ₱2,000 for a set of 5. Monthly retainers for ongoing thumbnail and banner creation range from ₱5,000-₱15,000.',
  'Create a thumbnail and banner portfolio: (1) Design 3 YouTube thumbnails for trending topics in the Philippines — use a bold face image (free stock from Unsplash), add a Taglish text overlay, and create a high-contrast color scheme. Use Canva plus AI image generation. (2) Create 2 Facebook ad banners (1200x628) for a Filipino business — one for a restaurant promotion and one for an online shop sale. (3) Design 1 Shopee shop banner (1200x300) for a fictional store. (4) For each piece, create 2 variations and note which one you think will perform better and why. (5) Add all pieces to your portfolio website from Module 1.',
  'Which type of visual (thumbnail, Facebook banner, or Shopee banner) was most challenging to design? How does thinking about click-through rates and A/B testing change the way you approach design? What makes a Filipino audience click differently from a Western audience?',
  3
from public.modules m where m.title = 'AI Visual Content';

-- Lesson 4
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Presentation Design with AI',
  'The Philippine BPO industry employs over 1.7 million people, and the startup ecosystem is growing rapidly — both sectors have an insatiable need for professional presentations. Pitch decks, client proposals, quarterly business reviews, training materials, and conference presentations are created daily by thousands of Filipino professionals who lack design skills. AI presentation tools transform this pain point into a profitable service. The top AI presentation tools: Gamma (gamma.app) generates complete presentations from a text prompt — describe your topic and audience, and it creates a visually cohesive deck in minutes with smart layouts, relevant images, and animations. The free tier gives you 400 AI credits (enough for approximately 40 presentations). Beautiful.ai (beautiful.ai) uses smart templates that automatically adjust formatting as you add content — no more fighting with slide layouts. Paid plans start at ₱700/month. Canva Presentations combine familiar Canva design tools with Magic Design for slides, making it easy to create branded decks that match your client visual identity. The professional workflow: (1) Client sends you a brief or raw content (bullet points, data, key messages). (2) Generate an initial deck using Gamma or Beautiful.ai. (3) Customize with client branding — colors, fonts, logo placement. (4) Enhance visuals using AI image generation for custom graphics and data visualization tools for charts. (5) Review for flow, storytelling, and impact. (6) Deliver in PowerPoint, PDF, and Google Slides format. Filipino business presentation culture values professionalism, warmth, and clarity. Avoid overly minimal Western-style decks — Filipino audiences respond to visually rich slides with clear data, professional imagery, and a personal touch. Training presentations for BPO companies should be engaging and interactive. Pitch decks for Filipino investors should lead with market opportunity and traction. Pricing structure: Simple presentation cleanup (10-15 slides): ₱3,000-₱5,000. Full presentation design from brief (15-25 slides): ₱8,000-₱15,000. Pitch deck with storytelling and strategy: ₱15,000-₱30,000. Training material packages: ₱10,000-₱20,000 per module. Monthly retainer for ongoing presentations: ₱12,000-₱25,000. The high value of presentations comes from their direct impact on business outcomes — a well-designed pitch deck can help raise millions in funding, and a compelling sales presentation can close deals worth hundreds of thousands of pesos.',
  'Build a presentation portfolio: (1) Sign up for Gamma (gamma.app) free tier. (2) Create a 12-slide pitch deck for a fictional Filipino startup — choose a food delivery service, health tech app, or education platform. Use Gamma for the initial generation, then customize. (3) Create a 10-slide training presentation for a BPO topic (customer service basics, time management, or communication skills) using Canva Presentations. (4) Export both presentations in PowerPoint and PDF format. (5) Add these to your growing portfolio with a brief description of the client brief and your design process.',
  'How did AI presentation tools compare to building slides manually in PowerPoint or Google Slides? Which tool (Gamma, Canva, or others) felt most powerful for your workflow? How could offering presentation design services complement your other AI content skills?',
  4
from public.modules m where m.title = 'AI Visual Content';

-- Lesson 5
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Selling Visual Content Services',
  'You now have a complete set of AI-powered visual content skills — social media design, image generation, thumbnails, banners, and presentations. The next step is packaging these skills into services that Filipino businesses want to buy. According to a 2025 survey by the Philippine Chamber of Commerce, 73% of Filipino small and medium businesses say they need better visual content but cannot afford a full-time designer. You are the affordable, AI-powered alternative. Design your service packages around client needs, not your tools. Clients do not care that you use Canva AI or Midjourney — they care about getting professional visuals quickly and affordably. Three proven package structures: The Social Media Kit (₱5,000/month) includes 20 social media posts, 4 story designs, and 1 monthly promotional banner. This is your entry-level package that gets clients in the door. The Brand Identity Package (₱15,000 one-time) includes logo design (3 concepts), brand color palette and typography guide, social media profile templates (Facebook, Instagram, TikTok), and 10 branded post templates. This is a high-value one-time project that often leads to monthly retainers. The Monthly Content Retainer (₱8,000-₱20,000/month) includes all social media visuals, thumbnails and banners as needed, presentation support, and monthly design consultation. This is your bread and butter — recurring revenue that compounds as you add clients. Finding clients in the Philippines: start with your existing network on Facebook. Post your portfolio with a clear call to action. Join Filipino freelancer and business owner groups on Facebook — there are dozens with 50,000+ members. List your services on local platforms: OnlineJobs.ph (for international clients), Facebook Marketplace (for local businesses), and Upwork (for a global client base). Cold outreach works: find local businesses with poor visual content on their social media and offer a free sample design. This is the same approach from the Pro track but now powered by AI for speed and quality. Pricing psychology: always present 3 options (Basic, Standard, Premium). The middle option should be your target — most clients choose it. Include a "per-design" rate for one-off requests (₱300-₱800 per design) as a gateway to monthly packages. Offer a 15% discount for 3-month commitments to lock in recurring revenue. Always quote in Philippine Pesos — foreign currency pricing creates friction for local clients.',
  'Launch your visual content service: (1) Finalize 3 service packages with clear deliverables, timelines, and prices — write them up professionally. (2) Create a simple service menu PDF using Canva (1-2 pages, visually appealing, includes your portfolio highlights). (3) Post your services in 3 Facebook groups for Filipino business owners or freelancers. (4) Send personalized messages to 5 local businesses offering a free sample design. (5) Set up a GCash Business account or Maya account for receiving payments — this removes friction for Filipino clients who prefer mobile payments over bank transfers.',
  'Looking at your three service packages, which one are you most excited to sell and why? What concerns do you have about pricing — are you tempted to charge less than your packages state? How does having AI as your production tool change your confidence in delivering professional results consistently?',
  5
from public.modules m where m.title = 'AI Visual Content';


-- ============================================================
-- MODULE 3 LESSONS: AI Video and Shorts
-- ============================================================

-- Lesson 1
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Script-to-Video with AI',
  'Video content drives 82% of all consumer internet traffic globally, and Filipinos are among the most active video consumers in the world — averaging 4 hours of online video watching daily. TikTok Philippines has over 50 million users, YouTube Philippines is the 4th largest YouTube market globally, and Facebook Reels are being pushed hard by Meta algorithm in the Philippine market. Every brand, business, and creator needs video content, but most cannot afford traditional video production. AI changes the economics completely. The script-to-video workflow: Start with Claude to write your video script. A strong AI prompt for scripts includes: topic, target audience, video length (30 seconds for Reels/Shorts/TikTok, 5-10 minutes for YouTube), tone, and call to action. Claude produces scripts with clear visual directions — what should appear on screen during each section. From there, tools like Pictory, Synthesia, InVideo AI, and HeyGen can convert your script into a finished video with stock footage, AI avatars, voiceover, music, and text overlays. The fastest workflow for short-form content (30-60 seconds): (1) Write script in Claude — 5 lines maximum for a 30-second video. (2) Generate visuals using InVideo AI or Pictory — paste the script, choose a style, and the AI matches stock footage to each line. (3) Add AI voiceover using ElevenLabs or the built-in TTS in CapCut. (4) Fine-tune in CapCut — add captions (mandatory for engagement — 85% of social media videos are watched without sound), transitions, and trending sounds. The economics: a single short-form video for a client takes 30-45 minutes to produce. Charge ₱1,500-₱3,000 per video. Produce 4 per day and you earn ₱6,000-₱12,000 daily. Monthly video content packages (12-20 short videos) sell for ₱15,000-₱40,000 in the Philippine market. For long-form YouTube content, the per-video rate increases to ₱5,000-₱15,000 depending on complexity. International clients on Upwork pay even more — $50-$200 USD per video. The skill you are building here — producing professional video content at AI speed — is one of the highest-demand freelance skills in 2026.',
  'Create your first AI-powered video: (1) Write a 30-second script using Claude about any topic relevant to Filipino audiences — a product review, a life tip, or a motivational message. (2) Sign up for a free trial of InVideo AI (invideo.io) or Pictory (pictory.ai). (3) Paste your script and generate a video. (4) Download the raw output and import it into CapCut (free). (5) Add auto-captions, adjust timing, and add one trending sound or music. Export the final video. The entire process should take under 45 minutes.',
  'How did the quality of your AI-generated video compare to manually edited videos you have seen on social media? What parts of the process required the most human judgment and creativity? Could you produce 4 of these per day once you build efficiency?',
  1
from public.modules m where m.title = 'AI Video and Shorts';

-- Lesson 2
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'CapCut AI for Professional Editing',
  'CapCut is the most used video editing app in the Philippines with over 30 million downloads — and its AI features make professional editing accessible to anyone with a smartphone. Understanding CapCut AI thoroughly separates amateur content from professional output, and it is the editing tool your clients expect you to know. Key AI features in CapCut: Auto-Captions generate accurate subtitles in English, Filipino, and Taglish. This single feature is critical — videos with captions get 80% more watch time. Enable captions on every video you produce. Auto-Reframe intelligently adjusts video aspect ratios for different platforms (9:16 for TikTok/Reels, 16:9 for YouTube, 1:1 for Facebook feed) without cutting off important content. Remove Background works in real-time during recording or on existing clips — replace your background with anything without a green screen. AI Effects include smart color correction, beauty filters (very popular in the Philippine market), and style transfers that make phone footage look cinematic. Text Templates offer animated text presets that match trending styles on TikTok and Instagram. Smart Clip Trimming uses AI to detect the most engaging moments in long footage and suggests cuts. The professional CapCut workflow: (1) Import raw footage or AI-generated video. (2) Apply auto-captions — edit for accuracy and style (font, size, position). (3) Add transitions between scenes — smooth cuts for professional content, trendy transitions for social media. (4) Color grade using AI presets — warm tones perform well for lifestyle content, cool tones for tech and business. (5) Add music from CapCut library (royalty-free) or client-provided audio. (6) Export at 1080p minimum — 4K for YouTube. Speed matters for profitability. A skilled CapCut editor can produce a polished 30-second social media video in 20-30 minutes and a 5-minute YouTube video edit in 2-3 hours. Client pricing: ₱1,500-₱3,000 per short-form video, ₱5,000-₱8,000 per long-form YouTube edit. Monthly editing retainers (8-12 videos): ₱15,000-₱30,000. At these rates, CapCut editing alone can generate ₱30,000-₱60,000 monthly with moderate client load.',
  'Master CapCut AI through practice: (1) Download CapCut (free) on your phone and computer. (2) Record a 60-second video of yourself sharing one tip about any topic — use your phone camera. (3) Edit the video using every AI feature: auto-captions (edit for perfect accuracy), background removal (replace with a professional background), color correction (try 3 different AI presets), and add animated text for key points. (4) Export in both 9:16 (TikTok/Reels) and 16:9 (YouTube) using Auto-Reframe. (5) Compare the original raw footage to the final edited version — notice the professional difference AI features make.',
  'How did using CapCut AI features change the quality of your raw footage? Which feature made the biggest visual impact? If you could edit 4-6 short videos per day at ₱2,000 each, how would that change your income situation?',
  2
from public.modules m where m.title = 'AI Video and Shorts';

-- Lesson 3
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Gemini Nano for Mobile Video',
  'Google Gemini Nano is the on-device AI model that runs directly on your smartphone — no internet connection required, no cloud processing fees, no subscription costs. For Filipino content creators, many of whom produce content primarily on their phones, this is transformative. According to a 2025 report by We Are Social, 98.5% of Filipino internet users access the web via mobile devices, making mobile-first content creation not just convenient but essential. Gemini Nano powers several video-enhancing capabilities on supported Android devices (Pixel 8+, Samsung Galaxy S24+, and expanding rapidly to more affordable phones). Smart video enhancement automatically adjusts lighting, stabilization, and color grading in real-time as you record — turning shaky, poorly lit phone footage into smooth, professional-looking video. Real-time audio enhancement reduces background noise (critical in the Philippines where recording in quiet environments is often impossible — traffic, karaoke, construction, and lively neighborhoods are constant). Smart composition suggestions guide you to frame shots better by analyzing the scene and suggesting optimal positioning. The practical mobile-first video creation workflow: (1) Plan your content using Claude on your phone (claude.ai works on mobile browsers). Write scripts, outlines, and shot lists during your commute. (2) Record using your phone camera with Gemini-powered enhancements active — smart HDR, Night Sight video, and audio denoising. (3) Edit directly in CapCut mobile — auto-captions, transitions, effects, all optimized for phone editing. (4) Generate supplementary visuals using DALL-E or Midjourney on your phone when you need B-roll or overlay images. (5) Schedule and publish from mobile using Buffer, Later, or native platform apps. No laptop required at any stage. This matters because many aspiring Filipino content creators and freelancers do not own a laptop — smartphones are their primary computing device. The "you need expensive equipment" barrier to video production is gone. A ₱15,000-₱25,000 smartphone with Gemini capabilities is your complete production studio. Combine phone recording with AI editing and you produce content that rivals creators spending ₱100,000+ on camera equipment. The business advantage: you can offer video content services to clients without a studio, without a laptop, and without a commute to an office. Record client testimonials on-site with your phone. Create restaurant content during a meal. Film product reviews at a client location. Mobile-first means you are always ready to create and earn. Filipino creators producing content with this workflow report earning ₱20,000-₱50,000 monthly from a combination of client work and their own channels.',
  'Set up your mobile production studio: (1) Enable all AI camera features on your Android phone — check Settings > Camera for any AI enhancement options. If on iPhone, enable Cinematic Mode and Action Mode. (2) Download Claude, CapCut, Canva, and your preferred scheduling app (Buffer or Later) on your phone. (3) Create a complete 60-second video entirely on your phone: write the script in Claude, record using AI camera enhancements, edit in CapCut with auto-captions and effects, create a thumbnail in Canva mobile. (4) Time yourself — aim for under 45 minutes from script to finished video. (5) Post the video on your personal TikTok or Instagram with a caption explaining your mobile-first workflow — this itself becomes portfolio content showing your capabilities.',
  'How does creating content entirely on your phone compare to using a laptop? What limitations did you encounter, and how did AI features help overcome them? If you can produce professional video content with just a phone, how does that change your perception of what equipment you need to succeed?',
  3
from public.modules m where m.title = 'AI Video and Shorts';

-- Lesson 4
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Faceless Content Channels',
  'Not everyone wants to be on camera — and you do not have to be. Faceless content channels are among the most profitable and scalable video business models. According to YouTube analytics data from 2025, faceless channels in niches like finance, motivation, technology, and top-10 lists achieve average RPMs (revenue per mille, or per 1,000 views) of ₱150-₱500 for Philippine audiences and $3-$12 for international English-language audiences. Some of the biggest YouTube channels in the Philippines are faceless — compilation channels, educational content, and AI-narrated stories. The faceless content production system: Scripting — use Claude to research and write scripts. Faceless content relies heavily on strong scripts because there is no personality or face to carry weak content. Every sentence must deliver value or curiosity. AI Voiceover — ElevenLabs (elevenlabs.io) produces natural-sounding voice narration in multiple accents and languages, including Filipino-accented English. The free tier gives you 10,000 characters per month (approximately 10 minutes of audio). Paid plans start at ₱500/month for unlimited voices. Alternative: use CapCut built-in text-to-speech for basic narration. Visual Production — combine stock footage (Pexels and Pixabay are free), AI-generated images (Midjourney or DALL-E), screen recordings, and animated text. InVideo AI and Pictory can auto-match visuals to your script, saving hours of manual editing. Assembly — CapCut or DaVinci Resolve (free, professional-grade) for final editing. Add captions (mandatory), background music (royalty-free from YouTube Audio Library), and branded intro/outro. Monetization strategies: YouTube Ad Revenue — requires 1,000 subscribers and 4,000 watch hours. Achievable in 3-6 months with consistent daily uploads. Affiliate Marketing — recommend products in your niche with affiliate links in the description. Sponsored Content — brands pay ₱5,000-₱30,000 per sponsored mention on channels with 10,000+ subscribers. Channel Flipping — build a monetized channel and sell it for 12-24x monthly revenue on marketplaces like Flippa. Client Services — produce faceless content for businesses that want a YouTube presence without putting their team on camera. Philippine-specific niches that work well for faceless channels: Filipino recipes and cooking, OFW financial tips, Philippine history and culture, Tagalog motivation and self-improvement, BPO career advice, and tech reviews in Taglish.',
  'Launch your first faceless content project: (1) Choose a niche from the list above or pick your own. Create a channel name and simple logo in Canva. (2) Write 3 video scripts using Claude — each 5-7 minutes long, researched and structured with clear hooks, sections, and conclusions. (3) Generate voiceover for one script using ElevenLabs free tier or CapCut TTS. (4) Assemble the video using stock footage, AI-generated images, and CapCut editing. Add captions and music. (5) Upload to YouTube as an unlisted video. Watch it back critically — does it feel professional enough to publish? What needs improvement?',
  'Would you rather build your own faceless channel or produce faceless content as a service for clients? What niche excites you most and why? How does removing the requirement to be on camera change your perception of content creation as a career?',
  4
from public.modules m where m.title = 'AI Video and Shorts';

-- Lesson 5
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Video Production as a Service',
  'Video is the highest-value content service you can offer. According to Wyzowl research, 91% of businesses use video as a marketing tool in 2026, and 96% of marketers say video has increased user understanding of their product. In the Philippines, businesses are rapidly shifting budget from static image advertising to video — Facebook Reels and TikTok ads consistently outperform image ads by 2-3x on engagement metrics. Yet professional video production in Manila still costs ₱20,000-₱100,000 per video from traditional agencies. Your AI-powered service undercuts these prices dramatically while delivering comparable quality. Service pricing structure: Single Short-Form Video (30-60 seconds, TikTok/Reels/Shorts): ₱1,500-₱3,000. Includes script, AI visuals or stock footage, voiceover or text overlay, captions, music, and editing. Production time: 30-45 minutes. Single Long-Form Video (5-10 minutes, YouTube): ₱5,000-₱15,000. Includes research, script, voiceover, visual assembly, captions, thumbnails, and description with SEO. Production time: 3-5 hours. Monthly Short-Form Package (12 videos): ₱15,000-₱25,000. Ideal for businesses wanting consistent TikTok/Reels presence. Monthly Full Package (4 long-form + 12 short-form): ₱30,000-₱50,000. Your premium offering for serious businesses. Content Calendar Management Add-On: ₱5,000/month extra for strategy, scheduling, and performance reporting. Client acquisition for video services: Start with businesses already creating poor-quality videos — restaurants filming on phones without editing, fitness instructors posting raw gym footage, e-commerce sellers with basic product walkthroughs. Offer a free "glow-up" of their worst-performing video to demonstrate the difference professional AI-assisted editing makes. This single free sample has a high conversion rate because the before-and-after is visually dramatic. Delivery workflow: (1) Client provides brief or raw footage. (2) You produce video using AI tools within 24-48 hours. (3) Client reviews via Google Drive or WeTransfer link. (4) One round of revisions included. (5) Final delivery in all required formats and sizes. Payment: 50% upfront, 50% on delivery via GCash, Maya, or bank transfer. For monthly packages, full payment at the start of each month. Scaling: once you have 3-5 video clients, you have a sustainable business earning ₱45,000-₱150,000 monthly. The skills from this entire module — script-to-video, CapCut mastery, mobile production, and faceless content — combine into a complete video production service that few Filipino freelancers can match in both speed and quality.',
  'Package and launch your video production service: (1) Write up your complete service menu with 4 packages — single short-form, single long-form, monthly short-form, monthly full package. Include prices, deliverables, turnaround times, and revision policy. (2) Create a 60-second promotional video for your own service using all the AI tools you have learned — this video IS your best portfolio piece. (3) Find 3 local businesses with weak video content on their social media. Download their worst video and create an improved AI-powered version as a free sample. (4) Approach these businesses with your free sample and service menu. (5) Post your promotional video and service details in 3 Filipino business or freelancer Facebook groups.',
  'Looking back across all 5 lessons in this module, which video production skill are you strongest in? Which needs more practice? If you could specialize in just one type of video service (short-form, long-form, faceless, or full-service), which would you choose and why? How does being able to produce video change your overall value as a content creator?',
  5
from public.modules m where m.title = 'AI Video and Shorts';


-- ============================================================
-- MODULE 4 LESSONS: AI Social Media Management
-- ============================================================

-- Lesson 1
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'AI-Powered Content Calendars',
  'A content calendar is the operational backbone of social media management. Without one, you are posting reactively — scrambling for ideas, missing optimal posting times, and producing inconsistent content that confuses algorithms and audiences alike. With AI, you can create a strategic 30-day content calendar in 30 minutes that would take a traditional social media manager 3-4 hours. The AI content calendar workflow: Step 1 — Strategic foundation. Prompt Claude with: "Create a 30-day social media content calendar for [business type] in the Philippines. Target audience: [demographics]. Goals: [brand awareness/sales/engagement]. Platforms: [Facebook/Instagram/TikTok]. Include content themes, post types (educational, promotional, entertaining, user-generated), and posting times optimized for Filipino audiences." Claude outputs a structured calendar with daily themes, post types, and caption directions. Step 2 — Content production. For each day, use your AI writing skills to generate captions and your AI visual skills to create graphics. Batch-produce a full week of content in a single 2-3 hour session. Step 3 — Scheduling. Use Buffer (free for up to 3 channels, paid plans from ₱350/month) or Later (free for up to 1 social profile) to schedule all content in advance. This means your client social media runs on autopilot while you focus on other clients or projects. Optimal posting times for Filipino audiences (based on 2025 Sprout Social data): Facebook — 1-3 PM weekdays, 12 PM weekends. Instagram — 11 AM-1 PM and 7-9 PM. TikTok — 7-9 AM, 12-3 PM, 7-11 PM. These times align with Filipino daily routines: lunch breaks, post-work relaxation, and late-night scrolling. The business impact: clients who follow a consistent content calendar see an average 67% increase in engagement within the first 60 days compared to random posting. When you present a client with a professional 30-day calendar — complete with post types, themes, captions, and graphics — you demonstrate organization and strategic thinking that justifies premium pricing. This differentiates you from the thousands of Filipino freelancers who offer "social media management" but just post randomly. Price your calendar service as part of monthly management packages (₱8,000-₱25,000/month) or sell standalone content calendar creation as a one-time service (₱5,000-₱10,000 per month of content).',
  'Create a complete 30-day content calendar: (1) Choose a real or fictional Filipino business — restaurant, salon, online shop, or gym. (2) Use Claude to generate the strategic framework: 30 days of themes, post types, and caption directions. (3) Produce content for the first 7 days: captions for Facebook, Instagram, and TikTok + design graphics in Canva. (4) Sign up for Buffer free tier and schedule all 7 days of content across platforms. (5) Document your time: how long did the calendar take? How long did production and scheduling take? Calculate what you would charge per hour if this were client work at ₱12,000/month.',
  'How does having a structured content calendar change the way you think about social media management? What was the most time-consuming part of the process — strategy, writing, design, or scheduling? How could you further streamline this workflow as you gain experience?',
  1
from public.modules m where m.title = 'AI Social Media Management';

-- Lesson 2
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Analytics and Reporting with AI',
  'Data separates professional social media managers from amateurs. According to HubSpot 2025 State of Marketing, businesses that make data-driven social media decisions see 23% higher ROI than those managing by intuition alone. Your ability to analyze performance data, identify trends, and present insights to clients is what keeps them paying month after month. The good news: AI makes analytics accessible even if you have zero statistics background. Data sources: Meta Business Suite (free) provides detailed analytics for Facebook and Instagram — reach, engagement, follower growth, post performance, audience demographics, and optimal posting times. TikTok Analytics (available for business accounts, free) tracks video views, profile views, follower growth, and audience insights. Shopee Seller Center provides product views, conversion rates, and traffic sources. Google Analytics (free) tracks website traffic and behavior for clients with websites. The AI analysis workflow: (1) Export data from each platform — most allow CSV download or you can screenshot key dashboards. (2) Feed the data to Claude with a prompt like: "Analyze this social media performance data for a Filipino restaurant. Identify the top 3 performing post types, the worst performing content, trends over the past 30 days, and 5 specific recommendations to improve engagement next month." Claude processes the data and provides insights that would take hours to derive manually. (3) Build a client report using Canva or Gamma — include key metrics with month-over-month comparison, top performing content, audience growth, and actionable recommendations. Professional reporting template: Page 1 — Executive Summary (3 bullet points of key results). Page 2 — Key Metrics Dashboard (reach, engagement rate, follower growth, click-through rate). Page 3 — Top and Bottom Performing Content (screenshots and analysis). Page 4 — Audience Insights (demographics, active times, behavior). Page 5 — Recommendations for Next Month (5 specific, actionable items). Deliver this report on the first of every month. It takes 1-2 hours to produce with AI assistance and is the single most important deliverable for client retention. Clients who receive monthly reports retain at a 78% rate versus 45% for those who do not. This report justifies your monthly fee because it makes your value visible and tangible.',
  'Build a practice analytics report: (1) If you manage any social media account (even your personal one), export the analytics data from Facebook Insights or Instagram Insights for the past 30 days. (2) If you do not have real data, use this sample data: 30 posts, average reach 450, engagement rate 4.2%, top post type was video (8.1% engagement), bottom was static image (2.3%), follower growth +127. (3) Feed the data to Claude and ask for analysis and recommendations. (4) Create a 5-page report in Canva or Gamma using the template structure above. (5) Time yourself — aim to complete the full report in under 90 minutes. Save this as a portfolio piece demonstrating your analytical capabilities.',
  'How does seeing social media through a data lens change your approach to content strategy? Which metric do you think matters most for Filipino small businesses — reach, engagement, or follower growth? How confident do you feel presenting data-driven recommendations to a client?',
  2
from public.modules m where m.title = 'AI Social Media Management';

-- Lesson 3
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Community Management at Scale',
  'Filipino social media is uniquely community-driven. The Philippines has been called the "Social Media Capital of the World," and this is reflected in how Filipinos interact with brands online — they expect personal responses, they build relationships through comments and DMs, and they are loyal to brands that make them feel seen. A 2025 Salesforce study found that 73% of Filipino consumers expect brands to reply to their social media messages within 4 hours. Community management — responding to comments, answering DMs, handling complaints, and fostering engagement — is one of the most time-consuming parts of social media management. It is also where AI assistance creates the biggest efficiency gain without sacrificing the personal touch Filipino audiences expect. AI-assisted comment responses: Use Claude to draft responses to common comment types. Create a response library organized by category: product questions ("What sizes are available?"), compliments ("Ang ganda naman!"), complaints ("Ang tagal naman ng delivery"), purchase inquiries ("Magkano po?" or "How to order?"), and spam (ignore or delete). For each category, generate 5-10 response templates in conversational Taglish that can be quickly personalized. A well-organized response library lets you handle 50+ comments in 15 minutes instead of an hour. DM management with ManyChat: ManyChat (manychat.com) automates Facebook Messenger and Instagram DM conversations. The free tier handles up to 1,000 contacts. Set up automated responses for common inquiries: store hours, product availability, pricing, order status, and booking requests. The automation handles 60-70% of messages; you personally respond to the rest. This saves 2-3 hours per day per client. Crisis handling protocol: negative reviews and complaints happen. Your AI-assisted crisis response: (1) Acknowledge immediately — "Thank you for letting us know. We take this seriously." (2) Move to DM — "Sending you a private message now to resolve this." (3) Use Claude to draft a thoughtful resolution response. (4) Document the issue for the client. Never ignore complaints and never delete negative comments (unless they are spam or harassment) — Filipino consumers notice and publicly call out brands that delete valid complaints. The community management service adds ₱5,000-₱10,000 per month to your social media management packages. Clients value it highly because it directly protects their brand reputation and drives sales through responsive customer service.',
  'Set up a community management system: (1) Create a Response Library in Google Sheets with tabs for: Product Questions, Compliments, Complaints, Purchase Inquiries, and General Comments. Generate 5 Taglish response templates per category using Claude. (2) Sign up for ManyChat free tier (manychat.com) and connect it to a Facebook Page (use your personal page or create a test page). (3) Build one automated flow: a greeting message that asks "How can we help?" with 3 button options (Products, Order Status, Talk to Us) — each leading to an appropriate response. (4) Write a Crisis Response Protocol document (1 page): steps to handle negative comments, escalation triggers, and template responses for common complaint types. (5) Practice: find 10 real comments on any popular Filipino business Facebook page and write personalized responses using your template library. Time yourself.',
  'How does AI-assisted community management change the quality and speed of brand responses? Do you think Filipino consumers can tell the difference between a template response and a personal one? How would you balance efficiency with authentic connection when managing a community?',
  3
from public.modules m where m.title = 'AI Social Media Management';

-- Lesson 4
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Influencer and UGC Campaigns',
  'Influencer marketing in the Philippines is a ₱12 billion industry growing at 30% year over year. Filipino consumers trust recommendations from real people far more than brand advertising — a 2025 Nielsen study showed that 88% of Filipino millennials have purchased a product based on an influencer recommendation. But you do not need celebrity influencers. Nano-influencers (1,000-10,000 followers) and micro-influencers (10,000-50,000 followers) deliver 4-8x higher engagement rates than macro-influencers and cost a fraction of the price. Nano-influencer rates in the Philippines: ₱1,000-₱5,000 per post, ₱2,000-₱8,000 per Reel/TikTok, and many accept free products in exchange for content (especially beauty, food, and fitness products). For a client spending ₱20,000 on an influencer campaign, you can engage 5-10 nano-influencers producing authentic content that reaches engaged, targeted audiences. AI tools for influencer campaign management: Influencer Discovery — use Claude to analyze and shortlist potential influencers. Prompt: "I need 10 Filipino nano-influencers (1K-10K followers) in [city] who post about [niche]. Suggest search terms and hashtags to find them on Instagram and TikTok." Then manually search those terms and evaluate profiles. Paid tools like HypeAuditor and Modash provide audience demographics and fake follower detection if your budget allows. Brief Creation — Claude generates professional influencer briefs in minutes: brand overview, campaign goals, content requirements, dos and don'ts, hashtags, and deadlines. A clear brief prevents miscommunication and ensures consistent brand messaging across all influencer content. Campaign Tracking — create a tracking spreadsheet with columns for each influencer: followers, engagement rate, posts delivered, reach achieved, clicks generated, and cost per engagement. Use Claude to analyze campaign results and generate a client report. UGC (User-Generated Content) strategy: encourage customers to create content about the brand by running hashtag campaigns, photo contests, or offering incentives (discount codes, feature on brand page). UGC is free content that builds social proof. AI helps you monitor UGC mentions, organize submissions, and identify the best content for reposting. Offering influencer campaign management adds ₱10,000-₱25,000 per campaign to your service menu. Most campaigns run 2-4 weeks, and the planning and management work is 8-15 hours total. This service positions you as a marketing strategist, not just a content creator — and strategic services command premium prices.',
  'Run a practice influencer campaign: (1) Choose a product or brand (real or fictional). (2) Use Instagram and TikTok search to find 5 nano-influencers in the Philippines who match the brand niche. Record their username, follower count, engagement rate (likes + comments / followers), and content style. (3) Use Claude to create a professional influencer brief for the campaign — include brand positioning, deliverables (1 post + 1 story), content guidelines, hashtags, and timeline. (4) Create a campaign tracking spreadsheet in Google Sheets. (5) Draft a DM outreach message to these influencers using Claude — the message should be professional, personal (reference their specific content), and clearly state the collaboration opportunity and compensation.',
  'How does influencer marketing feel different from other content creation services? Which part of the campaign process — discovery, briefing, or tracking — was most challenging? Could you see yourself managing influencer campaigns as a specialty service, or is it better as an add-on to your content management packages?',
  4
from public.modules m where m.title = 'AI Social Media Management';

-- Lesson 5
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Social Media Manager to Agency',
  'You have spent four lessons building comprehensive social media management skills — content calendars, analytics, community management, and influencer campaigns. Now it is time to think about scaling from one-person operation to a sustainable business that does not depend entirely on your personal hours. The math is simple: as a solo social media manager charging ₱12,000-₱15,000 per client per month, you can comfortably handle 4-5 clients before burnout — that is ₱48,000-₱75,000 monthly. But your income is capped by your time. To break through, you need to scale. Step 1: Systematize. Document every process as a Standard Operating Procedure (SOP). Content calendar creation SOP. Graphic design SOP (with Canva templates). Caption writing SOP (with Claude prompts). Scheduling SOP. Analytics and reporting SOP. Community management SOP. These SOPs are your business playbook — they allow anyone to replicate your quality standards. Use Notion (free) or Google Docs to organize them. Step 2: Tier your pricing. Basic Package (₱8,000-₱12,000/month): 15 posts per month, basic captions, scheduling, monthly report. Standard Package (₱15,000-₱20,000/month): 20 posts, short-form videos, community management, bi-weekly reporting. Premium Package (₱22,000-₱30,000/month): daily content, videos, community management, influencer campaigns, weekly reporting, strategy calls. The middle tier should be your target — it is the sweet spot of value and profitability. Step 3: Hire your first assistant. Filipino virtual assistants specializing in social media can be found for ₱8,000-₱15,000/month full-time. They handle scheduling, basic community management, and graphic production. You focus on strategy, client communication, and quality control. With one assistant, you can serve 8-10 clients instead of 4-5. Step 4: Scale to 5+ clients. Client acquisition should be systematic: 2 clients from referrals (ask every satisfied client for introductions), 2 clients from Facebook group networking and cold outreach, 1 client from portfolio and social media presence. At 8 clients averaging ₱18,000/month, that is ₱144,000 monthly revenue. Subtract ₱12,000 for an assistant and ₱5,000 for tools, and your profit is ₱127,000/month — equivalent to a senior manager salary in many Philippine corporations, with the freedom of running your own business. Step 5: Consider white-labeling. Other freelancers and small agencies may want to resell your services under their brand. You provide the work, they handle client relationships. This adds volume without adding direct client management overhead.',
  'Build your scaling blueprint: (1) Choose 3 of your most repetitive tasks and write detailed SOPs for each — include step-by-step instructions, tools used, time estimates, and quality checklists. Save in Notion or Google Docs. (2) Create your 3-tier pricing structure with clear deliverables, prices in pesos, and target client profiles for each tier. Design this as a 1-page PDF in Canva. (3) Draft a job listing for your first virtual assistant — include required skills, responsibilities, work hours, and salary range. Post it (or save it for when you are ready) on OnlineJobs.ph or Filipino VA Facebook groups. (4) Write down your 6-month client acquisition target: how many clients at which tier, and what is your target monthly revenue? (5) Identify your current biggest bottleneck — is it client acquisition, content production, or time management? Create a 30-day plan to address it.',
  'At what point does managing social media feel like a real business rather than freelance work? What is the biggest mental shift needed to go from "doing the work" to "managing the business"? Looking at your 6-month target, does it feel achievable — and what would reaching it mean for your life?',
  5
from public.modules m where m.title = 'AI Social Media Management';


-- ============================================================
-- MODULE 5 LESSONS: Building an AI Content Agency
-- ============================================================

-- Lesson 1
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Agency vs Freelancer Mindset',
  'There is a critical inflection point every successful Filipino freelancer reaches: the realization that trading time for money has a ceiling, and that ceiling is lower than your ambition. As a freelancer, you are the product. As an agency owner, you build systems that deliver the product — and those systems can scale beyond your personal capacity. The mindset shift is not about ego or titles; it is about economics. A freelancer earning ₱80,000/month is doing well. An agency earning ₱300,000/month with ₱200,000 in profit is building wealth. According to the Philippine Statistics Authority, there are 1.1 million registered micro, small, and medium enterprises in the Philippines — and fewer than 5% have a dedicated marketing partner. The market is enormous and underserved. Legal basics for starting an agency in the Philippines: DTI (Department of Trade and Industry) Business Name Registration costs ₱200-₱1,000 and takes 1-2 days. This is your minimum legal requirement for operating as a sole proprietor. BIR (Bureau of Internal Revenue) registration for tax compliance. Open a business bank account — BDO, BPI, and UnionBank offer SME accounts with low maintaining balances. If you plan to earn over ₱3 million annually, consider SEC registration as a corporation (costs ₱15,000-₱30,000 through a lawyer). Your professional brand matters. Create a business name that sounds like an agency, not a person — "Luzon Digital" hits differently than "Maria's Social Media." Design a simple logo, set up a professional email (you@youragency.com via Google Workspace at ₱280/month), and create a one-page website that showcases your services and portfolio. First impressions determine whether a prospect sees you as a ₱5,000/month freelancer or a ₱30,000/month agency. The agency model works because of leverage: you sell your expertise and systems, not just your hours. You charge agency rates (2-3x freelancer rates) because you deliver agency-level strategy, consistency, and reliability. Your AI tools are your competitive advantage — they give you the production capacity of a 3-person team at the cost of one person. Filipino businesses increasingly prefer working with agencies over individual freelancers because agencies feel more professional, more reliable, and less likely to disappear. Position yourself accordingly from day one, even if you are still a team of one.',
  'Take the legal and branding steps today: (1) Choose your agency name — brainstorm 10 options, then test them with 3 trusted friends. Check DTI name availability at bnrs.dti.gov.ph. (2) Register your business name with DTI online (₱200-₱500, done in 15 minutes). (3) Design a simple agency logo in Canva — clean, professional, memorable. (4) Set up a professional email via Google Workspace or create a free branded email using Zoho Mail. (5) Create a one-page website using Carrd (₱0-₱500/year) with: agency name and logo, services offered, 3 portfolio highlights, contact information and booking link (use Calendly free tier for client discovery calls).',
  'What does the word "agency" mean to you — and has your definition changed after this lesson? What fears come up when you think about positioning yourself as an agency rather than a freelancer? How does having legal registration and professional branding change your confidence?',
  1
from public.modules m where m.title = 'Building an AI Content Agency';

-- Lesson 2
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Productizing Your Services',
  'The biggest mistake freelancers-turned-agency-owners make is continuing to price by the hour or by custom quotes for every project. Hourly billing is a trap: the faster you get (and AI makes you very fast), the less you earn. Custom quoting is inefficient: every prospect requires a unique proposal, which consumes unbillable hours. The solution is productized services — fixed-scope, fixed-price packages that clients can understand and purchase like products. A productized service has three components: a clear deliverable (what the client gets), a fixed price (no negotiation or customization), and a defined timeline (when they receive it). This model benefits both sides: clients know exactly what they are buying and what it costs, and you know exactly what you need to deliver and what you will earn. Proven productized packages for an AI content agency in the Philippines: The Starter Kit (₱8,000 one-time) — brand audit, content strategy document, 10 social media templates in Canva, 7 days of caption content. Perfect for new businesses that need a foundation. The Content Engine (₱15,000/month) — 20 social media posts with captions and graphics, 2 short-form videos, monthly analytics report. Your bread-and-butter offering. The Growth Machine (₱28,000/month) — daily content across 3 platforms, 4 short-form videos, community management, influencer outreach, bi-weekly strategy call, monthly performance report. Premium tier for serious businesses. The AI Transformation Package (₱20,000 one-time) — set up AI chatbot on their Facebook page, create automated DM flows, build a content template library, train the client team on AI tools. High-value project-based work. Create a professional service menu — a 2-3 page PDF that looks like a restaurant menu. Clients choose what they want, you deliver it. No scope creep, no endless revisions, no ambiguity. Your onboarding workflow should also be productized: (1) Client fills out an intake form (Google Form with brand info, goals, target audience, access credentials). (2) You create their brand kit in Canva and prompt library in Claude within 24 hours. (3) First content batch delivered within 5 business days. (4) Monthly rhythm established: content delivery on the 25th, analytics report on the 1st, strategy call on the 5th. Client portals keep everything organized. Use Notion (free) to create a shared workspace for each client with their brand guidelines, content calendar, deliverables, and communication log. This professionalism is rare among Filipino freelancers and agencies — it becomes your competitive advantage.',
  'Productize your services now: (1) Design your service menu with at least 3 packages — use the pricing examples as starting points but adjust based on your local market research. Create it as a polished PDF in Canva. (2) Create a client intake form in Google Forms with 15-20 questions covering: business name, industry, target audience, current social media links, brand colors and fonts, goals, competitors, and content preferences. (3) Set up a Notion workspace template for client management — include sections for brand guidelines, content calendar, deliverables tracker, and meeting notes. Duplicate this template for each new client. (4) Write your onboarding email sequence: welcome email (sent after payment), intake form request, brand kit confirmation, and first delivery notification. Draft all 4 emails. (5) Calculate your capacity: how many clients on each tier can you handle solo? At what point do you need to hire?',
  'How does having fixed packages change the way you think about sales conversations? Does productized pricing make you feel more or less confident about your value? What was the hardest part of defining your packages — scope, pricing, or both?',
  2
from public.modules m where m.title = 'Building an AI Content Agency';

-- Lesson 3
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Client Acquisition Machine',
  'The number one reason Filipino freelancers and agencies fail is not lack of skill — it is inconsistent client acquisition. When you are busy with current clients, you stop marketing. When a client leaves, you scramble. The solution is building a client acquisition machine — a system that generates leads consistently, regardless of how busy you are with existing work. A 2025 survey by Freelancer.com Philippines found that 67% of successful Filipino freelancers earning over ₱100,000/month spend at least 5 hours per week on marketing and lead generation. Those earning under ₱30,000/month spend less than 1 hour per week. The correlation is clear. Channel 1: Cold Outreach (30% of leads). Identify 50 local businesses per month that need content help. Use AI to personalize outreach messages — Claude can analyze a business Facebook page and generate a custom message highlighting specific content gaps and opportunities. Template: "Hi [Name], I noticed [Business] has a strong following on Facebook but your last post was [X days ago]. We help businesses like [similar business] maintain consistent content that drives engagement. Would you be open to a 15-minute call to discuss how we could help?" Send 10 personalized messages per week. At a 5-10% response rate, that is 2-4 qualified conversations per month. Channel 2: LinkedIn Strategy (20% of leads). LinkedIn is growing fast among Filipino professionals and business owners. Post 3 times per week about social media tips, case studies, and behind-the-scenes agency content. Connect with local business owners and marketing managers. LinkedIn leads tend to be higher-value — companies, not individuals. Channel 3: Referral System (35% of leads). The most powerful acquisition channel. After delivering 30 days of great work, ask every client: "Do you know any business owners who could benefit from what we do for you?" Sweeten the deal: offer a 10% discount on next month for every referral that converts. Referral clients have 37% higher lifetime value because they arrive with built-in trust. Channel 4: Content Marketing (15% of leads). Produce content about your expertise on your own platforms. Short TikTok/Reels videos showing before-and-after client content, tips on social media strategy, behind-the-scenes of your AI workflow. This builds authority and attracts inbound leads over time. The weekly acquisition rhythm: Monday — send 3 cold outreach messages. Tuesday — post LinkedIn content and engage with connections. Wednesday — follow up on previous outreach and conversations. Thursday — post social media content for your own brand. Friday — review pipeline, update CRM, plan next week. Use a simple Google Sheets CRM: columns for lead name, business, contact method, status (cold/warm/proposal/client), last contact date, and notes. This systematic approach ensures you never have an empty pipeline.',
  'Build and activate your client acquisition machine: (1) Create your Google Sheets CRM with the columns listed above. Add 20 potential leads — local businesses you have identified that need content help. (2) Write 5 cold outreach message templates using Claude — each personalized for a different industry (restaurant, salon, clinic, gym, online shop). (3) Send your first 5 outreach messages this week — customize each template for the specific business. (4) Write and post your first LinkedIn article or post about a social media tip relevant to Filipino businesses. (5) Design your referral program: what discount or incentive will you offer existing clients for referrals? Write the referral ask script you will use after 30 days of service.',
  'Which client acquisition channel feels most natural to you — cold outreach, LinkedIn, referrals, or content marketing? Which one feels most uncomfortable, and why might that discomfort indicate an area of growth? How does having a systematic approach to finding clients change your anxiety about income stability?',
  3
from public.modules m where m.title = 'Building an AI Content Agency';

-- Lesson 4
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Hiring and Training Your First Team Member',
  'Hiring your first team member is the single most important scaling decision in your agency journey. According to a 2025 PayScale Philippines report, the average salary for a social media assistant in the Philippines is ₱12,000-₱18,000 per month full-time, with part-time options at ₱6,000-₱10,000. At the right time, this investment multiplies your capacity and revenue. The right time to hire: when you are consistently earning ₱60,000+/month, when you are turning away clients due to capacity, and when repetitive tasks (scheduling, basic design, community management) consume more than 50% of your work hours. Hire for repetitive execution, not strategy — you remain the strategist and client relationship manager. Where to find AI-literate talent in the Philippines: OnlineJobs.ph is the largest Filipino remote worker platform. Post a detailed job listing with clear requirements and salary range. Filipino VA Facebook groups (there are dozens with 10,000-100,000+ members) are excellent for finding candidates. University job boards at UP, DLSU, Ateneo, and UST for fresh graduates eager to learn. Your network — ask if anyone knows someone reliable and tech-savvy. What to look for in your first hire: basic Canva proficiency (trainable in 1 week with your SOPs), good written English and Filipino, reliability and communication (the most important trait — skills can be taught, discipline cannot), comfort with AI tools (or willingness to learn — younger candidates typically adapt fast), access to a reliable internet connection and a laptop or desktop computer. Training process: Week 1 — your new hire goes through all your SOPs, watching you work via screen share on each process. Week 2 — they execute tasks with you reviewing every deliverable. Week 3 — they work independently with you reviewing 50% of deliverables. Week 4 — they work independently with you reviewing 20% (spot checks). Document everything. Create Loom video recordings (loom.com, free tier) of each SOP being executed. These training videos reduce future hiring time from weeks to days. Quality control system: use a shared Notion board where every deliverable goes through "In Progress → Ready for Review → Approved → Delivered." You review before anything reaches the client. Over time, as your hire builds consistency, you reduce review frequency. Weekly 30-minute check-ins keep communication strong. The financial math: if your hire costs ₱15,000/month and enables you to take on 4 additional clients at ₱15,000 each, that is ₱60,000 in new revenue for ₱15,000 in cost — a 4x return on investment. This is how agencies scale: invest in people, multiply output, capture the margin.',
  'Prepare for your first hire: (1) Write a detailed job description for a "Content Production Assistant" — include responsibilities (Canva design, caption formatting, scheduling, basic community management), required skills, work hours, tools they need to know, and salary range. (2) Convert your top 3 SOPs into video tutorials using Loom (free) — record yourself walking through each process step by step. (3) Create an onboarding checklist in Notion: tool access setup (Canva, Buffer, Meta Business Suite), SOP training schedule (one SOP per day for Week 1), quality review process, and communication expectations. (4) Design a simple skills test for candidates: give them a client brief and ask them to create 3 social media posts in Canva within 45 minutes. This filters for both skill and speed. (5) Post the job listing on OnlineJobs.ph or 2 Filipino VA Facebook groups (or save the listing until you are ready to hire).',
  'How does the idea of hiring someone make you feel — excited, nervous, or both? What tasks would you be most relieved to hand off to an assistant? What is your timeline for making this hire based on your current income and client load?',
  4
from public.modules m where m.title = 'Building an AI Content Agency';

-- Lesson 5
insert into public.lessons (module_id, title, description, action_step, reflection_prompt, "order")
select m.id,
  'Scaling to 100K Pesos Per Month and Beyond',
  'Earning ₱100,000 per month puts you in the top 3% of income earners in the Philippines, according to the Philippine Statistics Authority. For context, the median Filipino family income is approximately ₱22,000 per month. Reaching ₱100,000 is not about working more hours — it is about building multiple revenue streams, stacking retainers, and creating leverage through automation and delegation. Here is the roadmap based on real Filipino agency owners who have achieved this milestone. Revenue Stream 1: Client Retainers (₱60,000-₱80,000/month). This is your core. You need 4-5 clients on monthly retainers averaging ₱15,000-₱18,000. Focus on retention over acquisition — it costs 5x more to find a new client than to keep an existing one. Deliver consistent results, send monthly reports, and conduct quarterly strategy reviews. Client lifetime should be 6+ months minimum. Revenue Stream 2: Project Work (₱15,000-₱25,000/month). Brand identity packages, website content, pitch decks, and campaign launches. These are one-time projects that fill revenue gaps and often convert into retainers. Keep 1-2 project slots open each month. Revenue Stream 3: Passive Products (₱5,000-₱15,000/month). Create and sell digital products: social media templates on Canva (earn ₱50-₱200 per sale), content calendar templates, AI prompt libraries, mini-courses on social media management, or Gumroad/Shopee digital product listings. These sell while you sleep and compound over time. A single template pack selling 5 copies per week at ₱500 each generates ₱10,000/month passively. Revenue Stream 4: Training and Consulting (₱5,000-₱15,000/month). As an established agency, businesses and aspiring freelancers will pay for your expertise. Offer 1-on-1 coaching sessions (₱2,000/hour), group workshops (₱1,500 per participant, 10 minimum), or corporate training for BPO companies and SMEs (₱15,000-₱30,000 per session). Automation is your profit multiplier. Every process you automate saves hours that can be redirected to revenue-generating activities. Zapier (free for 100 tasks/month) connects your tools — automatically save new client inquiries from your website to your CRM, send welcome emails when a client pays, and generate weekly performance digests. ManyChat handles repetitive client communication. Notion templates standardize operations. The combination of AI production tools, a trained team member, systematized operations, and diversified revenue streams creates a business — not just a job. Filipino agency case study: a 27-year-old from Davao started with one social media client at ₱5,000/month. Within 18 months, she scaled to 7 retainer clients, 2 template products on Shopee, and occasional corporate training — total monthly income: ₱147,000 with ₱35,000 in expenses (1 full-time assistant + tools). Net profit: ₱112,000 per month, working 30-35 hours per week. That trajectory started with the same skills you are building right now.',
  'Create your ₱100,000/month blueprint: (1) Map out your 4 revenue streams with realistic monthly targets for each. What does your income breakdown look like in 6 months? In 12 months? (2) Create one passive income product this week — a social media template pack in Canva (5-10 templates) that you can sell on Gumroad or your website. Price it at ₱499. (3) Calculate your current monthly expenses (tools, potential hires, subscriptions) and subtract from your revenue targets to determine net profit goals. (4) Identify your automation priorities — list 5 repetitive tasks in your workflow and research how Zapier, ManyChat, or Notion can automate them. Set up at least one automation this week. (5) Write your 12-month vision statement: where is your agency, how many clients, what is your monthly income, how many hours do you work per week, and how has your life changed? Print it and put it where you see it daily.',
  'Looking back at this entire AI Content Creation track — from your first AI-written caption to planning a ₱100,000/month agency — how has your perception of what is possible changed? What is the single biggest skill or mindset shift you have gained? If you achieve your 12-month vision, how will it impact not just your Money pillar, but your Mind, Body, and Spirit as well?',
  5
from public.modules m where m.title = 'Building an AI Content Agency';
